name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    env:
      ACCESS_KEY_ID: minioadmin
      SECRET_ACCESS_KEY: minioadmin
      ENDPOINT: 127.0.0.1:9000
      BUCKET_NAME: testbucket
    services:
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ROOT_USER: ${{ env.ACCESS_KEY_ID }}
          MINIO_ROOT_PASSWORD: ${{ env.SECRET_ACCESS_KEY }}
          MINIO_DEFAULT_BUCKETS: ${{ env.BUCKET_NAME }}
        ports:
          - 9000:9000
        options: --name minio-server

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        ACCESS_KEY_ID: ${{ env.ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ env.SECRET_ACCESS_KEY }}
        ENDPOINT: ${{ env.ENDPOINT }}
        BUCKET_NAME: ${{ env.BUCKET_NAME }}
        DIR_FILE_NAME: "_" # MinIO stores files in a filesystem so "." is not allowed
      run: go test -v ./...
